name: Trigger App Deployment

on:
  push:
    branches:
      - release
      - main
      - develop
  workflow_dispatch: # ◄ Allows you to trigger the build manually from the GitHub UI

jobs:
  call-central-workflow:
    uses: Nilesh-11/splitsmarter/ci-cd-workflows/.github/workflows/reusable-expo-deploy.yml@main
    with:
      branch_name: ${{ github.ref }}
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
