name: Trigger App Deployment

on:
  push:
    branches:
      - release
      - main
      - develop
  workflow_dispatch:

jobs:
  call-central-workflow:
    # Uses a relative path to reference a local workflow in the same repo
    uses: ./ci-cd-workflows/.github/workflows/reusable-expo-deploy.yml
    with:
      branch_name: ${{ github.ref }}
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
