name: Trigger App Deployment

on:
  push:
    branches:
      - release
      - main
      - develop
  workflow_dispatch:

jobs:
  call-central-workflow:
    # Format: <organization>/<repository-name>/.github/workflows/<file-name>@<branch-or-tag>
    uses: SplitSmarter/ci-cd-workflows/.github/workflows/expo-deploy.yml@main
    with:
      branch_name: ${{ github.ref }}
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
